import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:shamsi_date/shamsi_date.dart';

import 'date_formatter.dart';

class PdfReportBase {
  PdfReportBase._();

  static pw.Document createDocument() {
    // Compression helps keep share sizes small for WhatsApp and low bandwidth.
    return pw.Document(compress: true);
  }

  static pw.MultiPage buildPage({
    required String titleEn,
    required String titleFa,
    required List<pw.Widget> children,
    String? shopName,
    CalendarType calendar = CalendarType.gregorian,
    String locale = 'fa',
  }) {
    final generatedAt = calendar == CalendarType.persian
        ? _formatPersianDateTime(DateTime.now())
        : DateFormat('yyyy/MM/dd HH:mm', locale).format(DateTime.now());

    return pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(24),
      header: (context) => pw.Container(
        margin: const pw.EdgeInsets.only(bottom: 12),
        padding: const pw.EdgeInsets.only(bottom: 8),
        decoration: const pw.BoxDecoration(
          border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300)),
        ),
        child: pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Row(
              children: [
                pw.Container(
                  width: 26,
                  height: 26,
                  alignment: pw.Alignment.center,
                  decoration: pw.BoxDecoration(
                    color: PdfColors.blue700,
                    borderRadius: pw.BorderRadius.circular(13),
                  ),
                  child: pw.Text('H', style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold, fontSize: 13)),
                ),
                pw.SizedBox(width: 8),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Hesabat', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
                    pw.Text('$titleEn | $titleFa', style: const pw.TextStyle(fontSize: 10)),
                  ],
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                if (shopName != null && shopName.isNotEmpty)
                  pw.Text(shopName, style: const pw.TextStyle(fontSize: 10)),
                pw.Text(generatedAt, style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
              ],
            ),
          ],
        ),
      ),
      footer: (context) => pw.Container(
        margin: const pw.EdgeInsets.only(top: 10),
        padding: const pw.EdgeInsets.only(top: 8),
        decoration: const pw.BoxDecoration(
          border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
        ),
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated by Hesabat', style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
            pw.Text('Page ${context.pageNumber}/${context.pagesCount}', style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
          ],
        ),
      ),
      build: (context) => children,
    );
  }

  /// Format date and time in Persian (Jalali) calendar
  static String _formatPersianDateTime(DateTime date) {
    final jalali = Jalali.fromDateTime(date);
    final timeStr = DateFormat('HH:mm').format(date);
    return '${jalali.year}/${jalali.month.toString().padLeft(2, '0')}/${jalali.day.toString().padLeft(2, '0')} $timeStr';
  }
}
