-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_created_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone text NOT NULL UNIQUE,
  shop_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  passcode_hash text,
  notes text,
  first_login_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_created_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT admin_created_accounts_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT admin_created_accounts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.auth_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  event_type text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT auth_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shop_id uuid NOT NULL,
  name text NOT NULL,
  phone text,
  total_owed numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_interaction_at timestamp with time zone,
  sync_status text NOT NULL DEFAULT 'pending'::text,
  synced_at timestamp with time zone,
  local_id text,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.debt_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  debt_id uuid NOT NULL,
  shop_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_method text NOT NULL DEFAULT 'cash'::text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  currency text NOT NULL DEFAULT 'AFN'::text,
  sync_status text NOT NULL DEFAULT 'pending'::text,
  synced_at timestamp with time zone,
  CONSTRAINT debt_payments_pkey PRIMARY KEY (id),
  CONSTRAINT debt_payments_debt_id_fkey FOREIGN KEY (debt_id) REFERENCES public.debts(id),
  CONSTRAINT debt_payments_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.debts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shop_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  sale_id uuid,
  amount_original numeric NOT NULL,
  amount_paid numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'partial'::text, 'paid'::text, 'written_off'::text])),
  due_date date,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  amount_remaining numeric NOT NULL DEFAULT 0,
  last_reminder_sent_at timestamp with time zone,
  sync_status text NOT NULL DEFAULT 'pending'::text,
  synced_at timestamp with time zone,
  CONSTRAINT debts_pkey PRIMARY KEY (id),
  CONSTRAINT debts_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT debts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT debts_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shop_id uuid NOT NULL,
  device_id text NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['android'::text, 'ios'::text, 'web'::text, 'desktop'::text, 'unknown'::text])),
  app_version text,
  is_active boolean NOT NULL DEFAULT true,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT devices_pkey PRIMARY KEY (id),
  CONSTRAINT devices_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shop_id uuid NOT NULL,
  name text NOT NULL,
  barcode text,
  price numeric NOT NULL DEFAULT 0,
  stock_quantity numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name_dari text,
  name_pashto text,
  name_en text,
  cost_price numeric,
  min_stock_alert numeric NOT NULL DEFAULT 5,
  unit text NOT NULL DEFAULT 'piece'::text,
  category_id text,
  image_url text,
  expiry_date timestamp with time zone,
  prescription_required boolean NOT NULL DEFAULT false,
  dosage text,
  manufacturer text,
  color text,
  size_variant text,
  imei text,
  serial_number text,
  weight_grams numeric,
  sync_status text NOT NULL DEFAULT 'pending'::text,
  synced_at timestamp with time zone,
  local_id text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);
CREATE TABLE public.sale_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  product_id uuid,
  product_name_snapshot text NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  subtotal numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sync_status text NOT NULL DEFAULT 'pending'::text,
  synced_at timestamp with time zone,
  CONSTRAINT sale_items_pkey PRIMARY KEY (id),
  CONSTRAINT sale_items_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT sale_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shop_id uuid NOT NULL,
  customer_id uuid,
  total_amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'AFN'::text,
  payment_method text NOT NULL DEFAULT 'cash'::text CHECK (payment_method = ANY (ARRAY['cash'::text, 'credit'::text, 'mixed'::text])),
  is_credit boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  total_afn numeric,
  discount numeric NOT NULL DEFAULT 0,
  exchange_rate numeric NOT NULL DEFAULT 1,
  note text,
  created_offline boolean NOT NULL DEFAULT false,
  local_id text,
  synced_at timestamp with time zone,
  sync_status text NOT NULL DEFAULT 'pending'::text,
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id),
  CONSTRAINT sales_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.shops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid,
  name text NOT NULL,
  phone text,
  city text DEFAULT 'Kabul'::text,
  district text,
  shop_type text NOT NULL DEFAULT 'general'::text CHECK (shop_type = ANY (ARRAY['grocery'::text, 'pharmacy'::text, 'hardware'::text, 'electronics'::text, 'clothing'::text, 'bakery'::text, 'restaurant'::text, 'general'::text, 'other'::text])),
  currency_pref text NOT NULL DEFAULT 'AFN'::text,
  language_pref text NOT NULL DEFAULT 'fa'::text,
  subscription_status text NOT NULL DEFAULT 'trial'::text CHECK (subscription_status = ANY (ARRAY['trial'::text, 'active'::text, 'expired'::text, 'cancelled'::text, 'suspended'::text])),
  trial_ends_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  subscription_ends_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shops_pkey PRIMARY KEY (id),
  CONSTRAINT shops_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sync_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shop_id uuid,
  device_id text,
  op_id uuid,
  entity_type text,
  entity_id text,
  operation text,
  status text NOT NULL CHECK (status = ANY (ARRAY['queued'::text, 'success'::text, 'failed'::text, 'conflict'::text, 'skipped'::text])),
  message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sync_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT sync_audit_logs_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shops(id)
);